#!/usr/bin/env bash

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
filters=("$@") # Capture all arguments as an array
dry="0"

while [[ $# -gt 0 ]]; do
    if [[ "$1" == "--dry" ]]; then 
        dry="1"
    else 
        filters=("$1")
    fi
    shift
done

log() {
    if [[ "$dry" == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "Executing: $@"
    if [[ "$dry" == "1" ]]; then
        return
    fi
    "$@"
}

copy_file(){
    from=$1
    to=$2
    name=$(basename $from)

    execute rm -rf "$to/$name"
    execute cp "$from" "$to/$name"
}

log "-------------------- dev env ------------------------"

copy_dir .config "$HOME/.config"
