#!/usr/bin/env bash

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
filters=("$@") # Capture all arguments as an array
dry="0"

while [[ $# -gt 0 ]]; do
    if [[ "$1" == "--dry" ]]; then 
        dry="1"
    else 
        filters=("$1")
    fi
    shift
done

log() {
    if [[ "$dry" == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "Executing: $@"
    if [[ "$dry" == "1" ]]; then
        return
    fi
    "$@"
}

copy_dir(){
    from=$1
    to=$2

    pushd "$from" > /dev/null
        dirs=$(find . -mindepth 1 -maxdepth 1 -type d | sed 's|^\./||') # Remove './' prefix
        for dir in $dirs; do
            execute rm -rf "$to/$dir"
            execute cp -r "$dir" "$to/$dir"
        done
    popd > /dev/null
}

copy_file(){
    from=$1
    to=$2
    name=$(basename $from)

    execute rm -rf "$to/$name"
    execute cp "$from" "$to/$name"
}

log "-------------------- dev env ------------------------"

copy_dir .config "$HOME/.config"
copy_file .tmux.conf "$HOME"
copy_file .zshrc "$HOME"
