- hosts: localhost
  name: Macbook Playbook
  gather_facts: False
  vars:
    env: dev
    TFENV_ARCH: amd64
  tasks:
    - name: Ensures taps are present via homebrew
      community.general.homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items:
        - hashicorp/tap

    # - name: Update and Upgrade homebrew
    #   community.general.homebrew:
    #     update_homebrew: true
    #     upgrade_all: true

    - name: Ensures packages are present via homebrew cask
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - orbstack
        - iterm2
        - keepassx
        - slack
        - spacelauncher

    - name: Ensures packages are present via homebrew
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      with_items:
        - go
        - tmux
        - python
        - neovim
        - awscli
        - aws-sam-cli
        - neovim
        - stow
        - powerlevel10k
        - terraform
      ignore_errors: yes
      tags:
        - brew

    - name: Install linters and formatters with pip
      ansible.builtin.pip:
        name:
          - flake8
          - black
          - yamllint
        state: present
        executable: pip3

    - name: Install linters and formatters with npm
      loop:
        - eslint_d
        - prettier
      community.general.npm:
        name: "{{ item }}"
        global: true
        state: present

    - name: Run stow
      shell: "stow zsh nvim --target $HOME --verbose=2"
      register: result
      changed_when: 'result.stderr is search("LINK: ")'
      tags: stow
