
- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      - orbstack
      - iterm2
    brew_packages:
      - tmux
      - aws-sam-cli
      - neovim
      - go
      - node

    upgrade_homebrew_packages: true
  tasks:
    - name: Check if Homebrew is installed
      command: which brew
      register: brew_check
      failed_when: false
      changed_when: false

    - name: Install Homebrew
      command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      become: yes
      when: brew_check.rc != 0

    - name: Update Homebrew
      command: brew update
      when: upgrade_homebrew_packages

    - name: Upgrade Homebrew packages
      command: brew upgrade
      when: upgrade_homebrew_packages

    - name: "Installing Homebrew Casks"
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{ brew_cask_packages }}"

    - name: "Installing Homebrew packages"
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ brew_packages }}"



    # - name: Include tasks from another file
    #   include_tasks: tasks/test.yml


