#!/usr/bin/env bash

# Install cask packages
brew install --cask aerospace
brew install --cask amethyst
brew install --cask arc
brew install --cask bettertouchtool
brew install --cask ghostty
brew install --cask keepassxc
brew install --cask numi
brew install --cask orbstack
brew install --cask plex-media-server
brew install --cask qbittorrent
brew install --cask scroll-reverser
brew install --cask session-manager-plugin
brew install --cask slack
brew install --cask tad
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask zed
